### ISSUE TITLE
ImportError: cannot import name 'override' from 'typing' 

### ISSUE THREAD

**Issue by cainiaogoroad** [TUDB-Labs/mLoRA#215]
i excute this commad：python mlora.py   --base_model TinyLlama/TinyLlama-1.1B-Chat-v0.4   --config ./demo/dummy.yaml ，but it tell me：ImportError: cannot import name 'override' from 'typing' .

all output of this error are as follows:
![image](https://github.com/TUDB-Labs/mLoRA/assets/81227322/715a0fc7-b9a1-4382-bacb-6dea09d42ffe)

**Comment by yezhem** [comment]
upgrade the python version to 3.12
