### ISSUE TITLE
Failed to build installable wheels for some pyproject.toml based projects (sentencepiece) 这是为什么呢？

### ISSUE THREAD

**Issue by joyyyhuang** [TUDB-Labs/mLoRA#262]
![image](https://github.com/user-attachments/assets/3180712d-cb43-4d8d-855d-af9ac6597ccc)

**Comment by yezhengmao1** [comment]
it's an issue with compiling sentencepice, you should check the logfile

**Comment by joker666666666** [comment]
![image](https://github.com/user-attachments/assets/3179d499-4e52-4c2b-bf1f-1a72393b99a4)
是python版本的问题吗？我用的3.12.1

**Comment by yezhengmao1** [comment]
他那里写了：cmake command not found,安装 sentencepiece 需要编译代码，依赖cmake

**Comment by joker666666666** [comment]
![image](https://github.com/user-attachments/assets/f6b47a67-e4d8-4b66-a1b8-343f9647cd7c)
装了也不行哎 还要配置什么吗

**Comment by yezhengmao1** [comment]
这是 sentencepiece 的问题，你可以去那边问问。
你可以clean一下，在重新安装

**Comment by joker666666666** [comment]
![image](https://github.com/user-attachments/assets/7e456732-26cb-4633-ad8c-ab9386751264)
好像是 sentencepiece 版本的问题，我将 pyproject.mlora.toml 中 sentencepiece 的版本修改为 0.2.0 解决了这一问题。

**Comment by yezhengmao1** [comment]
能提一个 PR 改下版本么，我跑下流水线看看

**Comment by joker666666666** [comment]
好像跟机器也有关系，我在另一台A100的机器上没遇到这个BUG。上面这个BUG是在H20上遇到的。

**Comment by yezhengmao1** [comment]
sentencepiece 的问题
